### ISSUE TITLE
[Bug]: [1.19.2 Forge] Server Crash with modpack

### ISSUE THREAD

**Issue by RedBeast1959** [Fuzss/armorstatues#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

ArmorStatues-v4.0.0-1.19.2-Forge.jar

### Notes (Required)

Hi. Recently, I added Armor Statues mod with my on-going modpack with my friends. But when I shift-clicked armor stand, sever immediately crashed. I'm really sucked at reading crash / latest log, so could you help me to find which problem causes the crash? If there're too many mods, I will isolate them when I have enough time. Thanks in advance.

PuzzlesLib-v4.3.10-1.19.2
ArmorStatues-v4.0.0-1.19.2
rubidium-0.6.2.jar
oculus-mc1.19.2-1.2.8.jar
canary-mc1.19.2-0.0.4.jar
pluto-mc1.19.2-0.0.1.jar
saturn-mc1.19.2-0.0.1.jar
+@

Crash Report
https://gist.github.com/RedBeast1959/5ef52e5a26909a1353f90f207a80c2aa

Latest log
Below

### latest.log (Optional)

https://gist.github.com/RedBeast1959/2be98af7037571a78a0ba570e254ab46

**Comment by LolJohn11** [comment]
Same issue here.
Placed an armor stand, clicked on it and the game crashed.
[Crash report](https://bytebin.lucko.me/710YzQ405o)

**Comment by Fuzss** [comment]
This is because of a change in Forge 43.1.40. You can downgrade Forge for now, I'll have an update out within 24h.

**Comment by Fuzss** [comment]
Should be fixed in v4.0.1.
