### ISSUE TITLE
Shift right click or crouch right click doesnt work

### ISSUE THREAD

**Issue by krevesst** [Fuzss/armorstatues#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

According to the discription I am supposed to press shift and right click to open the menu, and an other youtuber said crouch and right click, but non of them work.

**Comment by Fuzss** [comment]
you need to hold a stick in the latest version.

**Comment by BeeFox-sys** [comment]
> you need to hold a stick in the latest version.

this should be updated in the mods description on mod platforms, i had to discover this issue to learn how to do this
