### ISSUE TITLE
[Suggestion]: Keybind options

### ISSUE THREAD

**Issue by sargeow** [Fuzss/armorstatues#11]
### Suggestion (Required)

Hey, just started using this mod along side a pretty heafty modpack and theres a conflict with ctrl/shift+right click and it wont let me access the config screen for the stands, it just places my armor set on the stand (prolly through some mod) 
Thanks!

**Comment by Fuzss** [comment]
You need to hold a stick

**Comment by sargeow** [comment]
oh, i must've glazed over that fact reading the mod page. my bad, though it does still seem like a sound idea

**Comment by sargeow** [comment]
it would seem the stick does not work

**Comment by Fuzss** [comment]
The armor stand tooltip should tell you. If it doesn‘t update to the latest version of the mod.

**Comment by sargeow** [comment]
ah there is a default config conflict with litematica, the 'tool' item is deafult stick, just had to change that and now all is working. sorry about that.

**Comment by sargeow** [comment]
![image](https://user-images.githubusercontent.com/89289084/221401070-0c7ac807-44b9-4191-80d9-1af9bcdcd9f7.png)
:D

**Comment by sargeow** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/89289084/221401084-c7cfd423-b94a-4c36-81a8-c79ce8f5282e.png)

**Comment by Fuzss** [comment]
Thanks for the feedback, will also include a config option for the item in the next version.

**Comment by sargeow** [comment]
Awesome! Thank you so much!!!
