### ISSUE TITLE
[Bug]: Configs Not Generating

### ISSUE THREAD

**Issue by AetheriMC** [Fuzss/armorstatues#12]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

It looks like the configs for this version of the mod are not generating for either the Client, Server, or Common. I've tried directly editing configs with Forge Config API and I've tried using the /CONFIG command to locate the files, but no such luck.

**Comment by Fuzss** [comment]
There are no configs for this mod. The description on CF is from my template for all mods.
