### ISSUE TITLE
[Suggestion]: Armor Swap

### ISSUE THREAD

**Issue by WimpieRatte** [Fuzss/armorstatues#19]
### Suggestion (Required)

I saw a different mod (Armor Stand Shift Swap) now enable shift+r-click to swap your current armor with that in the armor stand.
Not sure if this is an easy feature to implement into the armor statues mod?
Since the editing of an armor statue has been moved to you needing a stick equipped, maybe shift+r-click without a stick could work for such a feature?
Or perhaps a different hotkey even, if shift+r-click clashes with other mods?

**Comment by Fuzss** [comment]
I recently made such a project as a separate mod. 
You can find compiled jars for Forge and Fabric on our Discord. 
https://github.com/Fuzss/armorquickswap
