### ISSUE TITLE
[Bug]: Black Poses Previews when FancyMenu is Installed

### ISSUE THREAD

**Issue by LolJohn11** [Fuzss/armorstatues#2]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

**Current bug**
When configuring an armor stand in-game, the pose previews are covered in black "sectors", making it impossible to see the poses.
While narrowing down the cause of the bug, I discovered that it was FancyMenu that generated this bug, since removing that mod would solve the issue.
The armor stand entities (the poses themselves) seem to render behind those black sectors, as indicated by equipment poking through some of the pose previews when equipped to the armor stand.

**Steps to reproduce**
1. Have ArmorStatues and FancyMenu installed
2. Place an armor stand in the world
3. Shift-click on the stand and navigate to the Poses tab

**Screenshot of the bug**
![2022-10-16_12 27 53](https://user-images.githubusercontent.com/49366383/196028658-fef40682-81e5-4e15-8f8d-f25fcbbb477c.png)

**Comment by Fuzss** [comment]
Forwarded issue to FancyMenu, they take over a lot of the rendering on screens, these issues come from their changes.
https://github.com/Keksuccino/FancyMenu/issues/394

**Comment by Fuzss** [comment]
In the meantime it's maybe possible to blacklist this screen from FancyMenu? I'm not familiar with the mod much, but I think I've seen an option to do something like that.

**Comment by LolJohn11** [comment]
> Forwarded issue to FancyMenu, they take over a lot of the rendering on screens, these issues come from their changes. [Keksuccino/FancyMenu#394](https://github.com/Keksuccino/FancyMenu/issues/394)

I see, hoping it will be fixed soon.



> In the meantime it's maybe possible to blacklist this screen from FancyMenu? I'm not familiar with the mod much, but I think I've seen an option to do something like that.

I've looked both on their wiki and in the mod's config files, but have not found anything of the sort, unfortunately.

**Comment by LolJohn11** [comment]
Closing since the issue has been fixed on FancyMenu's side.
