### ISSUE TITLE
[Suggestion]: * Permissions/Ignore Permissions

### ISSUE THREAD

**Issue by sirblazzit** [Fuzss/armorstatues#25]
### Suggestion (Required)

Is it possible for this mod (Armor Statues) to be expanded to use * perms/option to ignore op and just try to run the commands regardless of permission?
I have the * perm in LuckPerms as most servers disable operator itself and rely on the * perm, but it tells me that I don't have permission, even though I have access to /data (and everything else, just not op).

**Comment by Fuzss** [comment]
There is a new config option for disabling the permissions check in v8.0.5.
