### ISSUE TITLE
[Suggestion]: Inventory GUI

### ISSUE THREAD

**Issue by sirblazzit** [Fuzss/armorstatues#26]
### Suggestion (Required)

Is it possible to create add a GUI that allows you to put an item onto an Armor Stand - Eg: Red Stained Glass Block on Head
Since when I shift + right click, it just takes off whatever piece of armor it's wearing

Edit:
Was just playing around on Singleplayer
There does appear to be some sort of GUI already built in, however possibly expanding the functionality to work on servers
Possibly by ignoring permissions and doing /modify effectively (idk how stuff works)

**Comment by Fuzss** [comment]
Changing equipment via a gui is possible as long as the mod is installed on the server, too.
