### ISSUE TITLE
[Bug]: Sneak right-clicking an armour stand takes the item/-s off of it as it opens the GUI on servers

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/armorstatues#30]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.0

### Minimal Setup (Required)

No

### Notes (Required)

While playing on a server shift right-clicking an armour stand grabs an item off of it at the same time as the GUI opens:

https://github.com/Fuzss/armorstatues/assets/86702831/6b8a5169-1b12-4cd6-9c81-54120052e2f1

I'm not sure if it's affected by any plugins or datapacks on the server, so I chose "no" to the previous question, but from what I understand there's nothing on the server I'm on that modifies this behaviour. The 2 relevant additions are [Advanced Armor Stands](https://www.spigotmc.org/resources/advanced-armor-stands.38513/) and the Vanilla Tweaks datapack. I have the Vanilla Tweaks integration enabled and everything works flawlessly, besides grabbing the items.

The person in #26 experienced the same issue, but didn't specify their server's details.

The issue doesn't happen in single-player so it's definitely something to do with servers. I tried without the mod and in both single-player and multi-player the item is grabbed when sneak right-clicking an armour stand, so maybe the mod fails to prevent that from happening in multi-player for whatever reason?

### latest.log (Required)

No relevant logs

**Comment by Fuzss** [comment]
This was caused by a change in Puzzles Lib, Armor Statues has now being update to handle this case correctly once again.
