### ISSUE TITLE
[Bug]: The mod's customization screen is entirely missing from the mod along with the textures, breaking the entire point of this mod.

### ISSUE THREAD

**Issue by MCAlexisYT** [Fuzss/armorstatues#31]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.5

### Minimal Setup (Required)

Yes

### Notes (Required)

The textures for the armor stand customization screen are literally missing from the jar file. And the customization screen doesn't open up at all. If it did, you would see eye-piercing checkerboards of magenta and black, which is better than **_HAVING THE ENTIRE F###ING ARMOR STAND CUSTOMIZATION SCREEN MISSING._**
I'm actually lying about the "minimal setup" one, because as I mentioned earlier, the entire `textures` folder is missing from the jar.

### latest.log (Required)

https://gist.github.com/MCAlexisYT/c4ef51684a37a1bd1d5523d339ded09e

**Comment by MCAlexisYT** [comment]
I went back to v8.0.0 and it actually works. Something clearly went horribly wrong with the project as a whole.

**Comment by Fuzss** [comment]
You need an empty hand when sneak+right-clicking on the armor stand. The empty hand might not have been required in earlier versions. The textures are fine, they are not supposed to be in the root assets directory.

**Comment by MCAlexisYT** [comment]
> You need an empty hand when sneak+right-clicking on the armor stand. The empty hand might not have been required in earlier versions. The textures are fine, they are not supposed to be in the root assets directory.

**_THE TEXTURES LITERALLY DON'T F#%(*ING EXIST!_**

**Comment by MCAlexisYT** [comment]
![image](https://github.com/Fuzss/armorstatues/assets/78766083/8bdf85ea-d6c4-4668-b8f7-6542efd77890)

**Comment by MCAlexisYT** [comment]
![image](https://github.com/Fuzss/armorstatues/assets/78766083/5c53191d-fc5e-43e3-b158-381e89aceedc)
