### ISSUE TITLE
[Crash]: Armor Statues

### ISSUE THREAD

**Issue by XanderCrafter** [Fuzss/armorstatues#36]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.0

### Minimal Setup

⸺

### Notes (Required)

Game started crashing due to Armor Statues issue after installing newest version of PuzzleLib.

### Crash Report (Required)

https://pastebin.com/kwBQfg5F

**Comment by XanderCrafter** [comment]
Actually, in trying to isolate the problem, I've found that Cut Through also doesn't work with the new PuzzleLib.  Me guess is that many of your mods might have an issue with it.

**Comment by Fuzss** [comment]
You have to update Forge Config Api Port.
