### ISSUE TITLE
[Crash]: Client crash when opening armor statues 1.21

### ISSUE THREAD

**Issue by Hiusi** [Fuzss/armorstatues#37]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21

### Minimal Setup

No

### Notes (Required)

I could be wrong, but either Carry on or Doggy talent next make the game crash, the crash is so unpredictable sometimes when you join and shift right click, it just showing fine, but after playing 15 mins or so, the game crash, and when I tried with carry on and dtn the crash is happening more frequently so I put the minimal setup to no

### Crash Report (Required)

https://mclo.gs/Rx036ph

**Comment by Fuzss** [comment]
Does installing this mod in addition to Armor Statues fix the issue?
https://mega.nz/file/PUMl2ThA#OYRzznOs2E_koT422E_gUW0rjIputs2R-MySqX1PPqk

**Comment by Hiusi** [comment]
I will try it once I got home! thank you for the solution

**Comment by Hiusi** [comment]
I tried to play it for 3 hours, and NO SINGLE CRASHES!! thank you for the hardwork

**Comment by SOMEHOTMEAL** [comment]
@Fuzss hi, the same problem is happening for me on the newer version

**Comment by Fuzss** [comment]
Published as v21.0.1.
