### ISSUE TITLE
[Crash]: Armorstatues Carashes when using owo lib on a server

### ISSUE THREAD

**Issue by SmoothTurtle872** [Fuzss/armorstatues#38]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.0

### Minimal Setup

No

### Notes (Required)

1.  Install owo lib and armorstatues onto client
2. Join a server that ***does not*** have armorstatues
3. Open an armorstand menu with shift rightclick (You may need op privileges, the server I was on, for repeatable results, is legitimoose.com create a world in it and attempt to open an armorstand)

### Crash Report (Required)

https://gist.github.com/SmoothTurtle872/b704bd24e64b53060022ce91b57116c6

**Comment by Fuzss** [comment]
Does installing this mod in addition to Armor Statues fix the issue?
https://mega.nz/file/PUMl2ThA#OYRzznOs2E_koT422E_gUW0rjIputs2R-MySqX1PPqk

**Comment by SmoothTurtle872** [comment]
I will try when I get home

**Comment by SmoothTurtle872** [comment]
It works! TYSM for the fix!
