### ISSUE TITLE
[Bug]: statuesmenu file is missing for straw statues and armor statues

### ISSUE THREAD

**Issue by SOMEHOTMEAL** [Fuzss/armorstatues#40]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.1

### Minimal Setup (Required)

No

### Notes (Required)

when trying to launch minecraft with either of these mods the game crashes when initializing. it says statuemenus failed somewhere and java.lang.RuntimeException is the error

### latest.log (Required)

https://gist.github.com/SOMEHOTMEAL/49d1f6ca2d919d8861dc45ed34ec2d70

**Comment by Fuzss** [comment]
There is no error in your log. Please post a proper crash report.

The only thing I can see is that apparently you manually installed Statue Menus from somewhere and Fabric Loader seems to prefer that. Don't do that, the correct version is bundled in the mods that use it.

**Comment by SOMEHOTMEAL** [comment]
this is the crash report:     https://gist.github.com/SOMEHOTMEAL/99b48a1600817682550536e7aadb5797
and this is the latest log:  https://gist.github.com/SOMEHOTMEAL/65456d5687354ae3eb0a6c3d9ee1cc1b

**Comment by SOMEHOTMEAL** [comment]
ok so i found the problem, for some reason the mod armorposer just decided it would make it stop working
