### ISSUE TITLE
[Bug]: Is this helmet size intentional?

### ISSUE THREAD

**Issue by Psychodeus** [Fuzss/armorstatues#6]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

![2022-11-09_01 59 28](https://user-images.githubusercontent.com/93028949/200640743-7bd00b56-1288-4232-933a-82502fa822fc.png)

I check the small figure, and it looks like the helmet is too big for it. Is this intentional?
Can I get the overall small size?

**Comment by Fuzss** [comment]
I don’t change rendering, that’s all vanilla. The head of baby mobs intentionally has the same dimensions as the adult‘s head.
