### ISSUE TITLE
[Bug]: Tablist doesnt work

### ISSUE THREAD

**Issue by Zoltus** [Fuzss/armorstatues#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.2

### Notes (Required)

When having the mod, tablist doent work anymore. client log doesnt throw any errors.

**Comment by Fuzss** [comment]
Reconfigure the cycle tabs keybind for now, it is conflicting with the tablist.

I'll probably just hardcode the tab key for cycling armor statues tabs in the next version so there is no longer a keybind that can conflict.
