### ISSUE TITLE
[Crash]: Minecraft crashes on start

### ISSUE THREAD

**Issue by AdeptusAutumn** [Fuzss/armorstatues#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

I start the game via the launcher and after a couple seconds it crashes. The game window itself wont even open. 

### Crash Report (Required)

https://mclo.gs/9hGETVl

### latest.log (Optional)

https://mclo.gs/5eubzJv

**Comment by Fuzss** [comment]
Remove Charm, it seems to breaking a lot of my mods (also other ones). Looks like an issue they can only fix on their end.
